# Generated by Django 4.0.5 on 2022-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField(verbose_name='original link')),
                ('shortened_link', models.URLField(verbose_name='original link')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name_plural': 'shorten urls',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['id'], name='shortenurl__id_d2e0a0_idx'),
        ),
    ]
