# Generated by Django 4.0.5 on 2022-06-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortened_link',
            field=models.URLField(blank=True, null=True, verbose_name='original link'),
        ),
    ]
